const { GoogleGenerativeAI } = require('@google/generative-ai');

class AiProvider {
  constructor() {
    this.apiKey = process.env.GEMINI_API_KEY;
    if (this.apiKey) {
      this.genAI = new GoogleGenerativeAI(this.apiKey);
      // We use the recommended text generation model
      this.model = this.genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
    }
  }

  async generateItinerary(requestData) {
    if (!this.apiKey) return this._mockGenerateItinerary(requestData);

    try {
      const prompt = `
        You are an expert travel planner. I will provide you with verified travel data, including places, flights, hotels, and user preferences.
        Generate a strictly structured daily itinerary for this trip.

        User Preferences:
        - Origin: ${requestData.origin}
        - Destinations: ${requestData.destinations.join(', ')}
        - Dates: ${requestData.startDate} to ${requestData.endDate}
        - Budget: ${requestData.budget}
        - Travelers: ${requestData.travelers}
        - Interests: ${requestData.interests.join(', ')}
        - Travel Style: ${requestData.travelStyle}

        Available Verified Places:
        ${JSON.stringify(requestData.places, null, 2)}

        Constraints:
        - DO NOT invent prices or places.
        - Geographically cluster activities for each day to minimize travel time.
        - Output the result as a valid JSON string (no markdown formatting, just raw JSON) matching this exact schema:
        {
          "dailyPlan": [
            {
              "day": 1,
              "date": "YYYY-MM-DD",
              "city": "City Name",
              "morning": [{ "placeId": "id", "name": "Name", "time": "09:00", "estimatedCost": 0, "notes": "Why..." }],
              "afternoon": [...],
              "evening": [...]
            }
          ],
          "tripInsights": [
            "Insight 1 (e.g. Weather is great for Day 2 outdoor activities)",
            "Insight 2 (e.g. Budget is slightly stretched, consider fewer paid activities)"
          ],
          "estimatedTotalCost": 12000
        }
      `;

      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      let text = response.text();
      // Clean up markdown block if present
      text = text.replace(/```json/gi, '').replace(/```/g, '').trim();
      return JSON.parse(text);
    } catch (error) {
      console.error('Gemini AI Generation Error:', error.message);
      return this._mockGenerateItinerary(requestData);
    }
  }

  _mockGenerateItinerary(requestData) {
    console.log('[AiProvider] Using mock AI generation rule engine');
    
    // Very basic rule engine fallback
    const dailyPlan = [];
    let currentDay = new Date(requestData.startDate);
    const end = new Date(requestData.endDate);
    
    let dayNum = 1;
    while (currentDay <= end) {
      const dateStr = currentDay.toISOString().split('T')[0];
      const city = requestData.destinations[0] || 'Unknown City';
      
      dailyPlan.push({
        day: dayNum,
        date: dateStr,
        city: city,
        morning: [
          { placeId: `mock_${dayNum}_m`, name: `${city} Morning Attraction`, time: '09:30', estimatedCost: 500, notes: 'Geographically clustered.' }
        ],
        afternoon: [
          { placeId: `mock_${dayNum}_a`, name: `${city} Afternoon Museum`, time: '14:00', estimatedCost: 1500, notes: 'Fits your cultural interest.' }
        ],
        evening: [
          { placeId: `mock_${dayNum}_e`, name: `${city} Local Dinner`, time: '19:00', estimatedCost: 2000, notes: 'Highly rated food.' }
        ]
      });
      
      currentDay.setDate(currentDay.getDate() + 1);
      dayNum++;
    }

    return {
      dailyPlan,
      tripInsights: [
        `This is a mock itinerary generated by the fallback rule engine.`,
        `Configure GEMINI_API_KEY for intelligent AI-driven geographic optimization.`
      ],
      estimatedTotalCost: dayNum * 4000
    };
  }
}

module.exports = new AiProvider();
